### ISSUE TITLE
Ревью v1

### ISSUE THREAD

**Issue by febos** [DmitryInd/project_Quest#3]
При запуске получил такое:
Главный экран
Выберите сюжет (выйти - exit):
1) VeryCoolGame2
2) Свой
1
Traceback (most recent call last):
  File "/home/baulin/Desktop/PythonFIVT/Review1/Indenbom/project_Quest-dev/Main.py", line 221, in <module>
    raise f
  File "/home/baulin/Desktop/PythonFIVT/Review1/Indenbom/project_Quest-dev/Main.py", line 216, in <module>
    selected_story('Information\\' + variants[int(f_answer) - 1])
  File "/home/baulin/Desktop/PythonFIVT/Review1/Indenbom/project_Quest-dev/Main.py", line 141, in selected_story
    fairy = codecs.open(name_story, 'r', 'utf-8')
  File "/usr/lib/python3.4/codecs.py", line 891, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: 'Information\\VeryCoolGame2.txt'

Переделайте задание путей с учетом любой ОС пользователя

**Comment by DmitryInd** [comment]
Очень странно, в программе используются относительные пути и такой ситуации по идее быть не должно.Попробуйте использовать прикреплённый к письму архив (предварительно распаковав), возможно я не прикрепил в github какие-либо файлы. 04.04.2019, 01:12, "febos" <notifications@github.com>:При запуске получил такое:Главный экранВыберите сюжет (выйти - exit):VeryCoolGame2Свой1Traceback (most recent call last):File "/home/baulin/Desktop/PythonFIVT/Review1/Indenbom/project_Quest-dev/Main.py", line 221, inraise fFile "/home/baulin/Desktop/PythonFIVT/Review1/Indenbom/project_Quest-dev/Main.py", line 216, inselected_story('Information\' + variants[int(f_answer) - 1])File "/home/baulin/Desktop/PythonFIVT/Review1/Indenbom/project_Quest-dev/Main.py", line 141, in selected_storyfairy = codecs.open(name_story, 'r', 'utf-8')File "/usr/lib/python3.4/codecs.py", line 891, in openfile = builtins.open(filename, mode, buffering)FileNotFoundError: [Errno 2] No such file or directory: 'Information\VeryCoolGame2.txt'Переделайте задание путей с учетом любой ОС пользователя—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by DmitryInd** [comment]
Понял, в чём проблема.Залил на github правку (проверить сам работоспособность не на Windows не могу) 04.04.2019, 01:20, "Дмитрий Инденбом" <dmitry.indenbom@yandex.ru>:Очень странно, в программе используются относительные пути и такой ситуации по идее быть не должно.Попробуйте использовать прикреплённый к письму архив (предварительно распаковав), возможно я не прикрепил в github какие-либо файлы. 04.04.2019, 01:12, "febos" <notifications@github.com>:При запуске получил такое:Главный экранВыберите сюжет (выйти - exit):VeryCoolGame2Свой1Traceback (most recent call last):File "/home/baulin/Desktop/PythonFIVT/Review1/Indenbom/project_Quest-dev/Main.py", line 221, inraise fFile "/home/baulin/Desktop/PythonFIVT/Review1/Indenbom/project_Quest-dev/Main.py", line 216, inselected_story('Information\' + variants[int(f_answer) - 1])File "/home/baulin/Desktop/PythonFIVT/Review1/Indenbom/project_Quest-dev/Main.py", line 141, in selected_storyfairy = codecs.open(name_story, 'r', 'utf-8')File "/usr/lib/python3.4/codecs.py", line 891, in openfile = builtins.open(filename, mode, buffering)FileNotFoundError: [Errno 2] No such file or directory: 'Information\VeryCoolGame2.txt'Переделайте задание путей с учетом любой ОС пользователя—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by febos** [comment]
Проект принят с 1 доп баллом
